
  eureka: 
    instance:
     hostname: ${eureka.instance.hostname}
     securePort: ${server.port}
     securePortEnabled: true 
     nonSecurePortEnabled: true 
     secureVirtualHostName: ${spring.application.name}
     homePageUrl: http://${eureka.instance.hostname}:${server.port}/
     statusPageUrl: http://${eureka.instance.hostname}:${server.port}/admin/info

     metadataMap:
       hostname : ${eureka.instance.hostname}
       securePort: ${server.port}
    
    client: 
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/